apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runner
  namespace: actions
spec:
  replicas: 1
  template:
    spec:
      repository: majid1010/demo-open-api
      env: []
