name: Demo API App CI pipeline

on:
  push:
  pull_request:
    branches: 
      - main
  workflow_dispatch:
  
jobs:
  build_repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: verify configs
        run: echo "code is checked out"
        shell: bash
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: CleanUp
        run: pwd & ls -la
        shell: bash

      
