name: Kubernetes Single Runner Demo
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build
    runs-on: my-self-hosted-deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Do Something
        run: |
          echo "Hello! self-Hosted Runner Deployment!"
          uname -a 
          printenv